services:
  - type: web
    name: banco-genio
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir Apps app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_SECRET_KEY
        generateValue: true
